### PR TITLE
Update OpenLayers --> latest v9.2.4

### PR DESCRIPTION
**Pull request by spwoodcock**
- Anticipates merge of https://github.com/openlayers-elements/openlayers-elements/pull/109
- Updates to OpenLayers v9.2.4, checking for deprecations and breaking changes.
- v8 has breaking changes and deprecations, but none that affected us. It also adds FlatStyle styling.
- v9 has no breaking changes.

### Todo

- [x] Update `ol-marker-icon.ts` to flat style format.
- [x] Remove @types/ol and replace with types bundles directly in `ol` package.

### CODE REVIEW

**Comment by spwoodcock** [comment]
It was a bit of a pain to work with the new OpenLayers flat styling, due to it not being supported through the entire library yet:
- Styling `Feature`s does not support flat style.
- The types for flat styling also don't support the gradient and pattern we use in `styled-map.ts`.
- I created a few helper functions to convert from flat style to standard ol Style where necessary, as a workaround until there is better support.

All tests pass after the upgrade & I added a changeset 👍

**Comment by spwoodcock** [comment]
I updated the CDN link for the bundled styles in ol-map to v9.2.4 also.

I was trying to see if there was a better way to bundle the styles, rather than relying on the CDN.

I tried many approaches:
- `import 'ol/ol.css'.
- Embedding `ol.css` in a Lit `css` template literal.
- Creating a `style.css` file and using `@import "node_modules/ol/ol.css"` import (as advised in the docs).

I couldn't get the styles to load correctly! I'm sure there is a better way, but for now I kept it as the same CDN-based approach.

**Comment by tpluscode** [comment]
Please resolve conflicts @spwoodcock

**Comment by spwoodcock** [comment]
Agree!

**Pull request merged**
