### PR TITLE
Replace wsrun (yarn-specific) with npm workspaces

### PR DESCRIPTION
**Pull request by spwoodcock**
## Issue

- I do not have `yarn` installed on my system, and `wsrun` appears to be yarn-based.
- I was receiving an error when attempting to build, suggesting that yarn is required to use `wsrun`:

```
Error: spawn yarn ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:286:19)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:292:12)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn yarn',
  path: 'yarn',
  spawnargs: [ 'start' ]
}
```

## Solution

- As we agreed to replace `yarn` with standard `npm`, I also replaced `wsrun`.
- I decided to just do something quick that works (so I can start on the openlayers upgrades), and replaced wsrun with [lerna](https://github.com/lerna/lerna).
- Lerna is a tool for managing multiple packages from the same repo (like we have).
- We can discuss if we wish to keep Lerna, or replace with another tool.

### CODE REVIEW

**Comment by tpluscode** [comment]
Hm, I used lerna before npm supported workspaces. Right now, I find it an overkill. Just look at the `package.json` diff

Truly, why is it an issue to have yarn installed? It appears so ubiquitous that even github's `action/setup-node` installs it by default...

**Comment by tpluscode** [comment]
I just found that there is, slightly hacky, way to use `npm` with `wsrun`: https://github.com/hfour/wsrun/issues/105

Also, maybe we it would be acceptable to add yarn as peer dependency?

**Comment by tpluscode** [comment]
How would you rewrite the `build` script?

**Comment by ludovicm67** [comment]
This could be a way:

```diff
@@ -9,14 +9,14 @@
   ],
   "scripts": {
     "prestart": "npm run analyze",
-    "start": "wsrun -p demos -c start",
-    "build": "wsrun -x demos -x @openlayers-elements/testing -c build",
+    "start": "npm --workspace demos run start",
+    "build": "npm -w @openlayers-elements/core -w @openlayers-elements/maps -w @openlayers-elements/swisstopo -w @openlayers-elements/bundle run build",
     "lint": "eslint --ext .ts,.js elements demos --quiet",
     "test": "wtr",
     "preanalyze": "tsc",
     "analyze": "polymer analyze --sources elements > demos/public/analysis.json",
     "predocs": "npm run analyze",
-    "docs": "wsrun -p demos -c build",
+    "docs": "npm --workspace demos run build",
     "release": "changeset publish",
     "prepare": "husky"
   },
@@ -39,8 +39,7 @@
     "lint-staged": "^13.0.3",
     "polymer-cli": "^1.9.11",
     "prettier": "^1.16.4",
-    "typescript": "^5.4.5",
-    "wsrun": "^5.2.4"
+    "typescript": "^5.4.5"
   },
   "lint-staged": {
     "*.{ts,js}": [
```

The build script might be improved in the future.

**Comment by tpluscode** [comment]
With just a handful packages, explicitly calling them can work

**Comment by spwoodcock** [comment]
Thanks for the input guys!
I have never had to handle multiple packages in the same repo before, so never used workspaces.
Good solution @ludovicm67 🎉 I will update the PR.

@tpluscode I could install `yarn`, it's just not added as a dependency in my standard dev docker image 😅 
Personally I think that `yarn` should never have been made (hence my hesitation to use it) - it fragments the packaging system & adds no real benefit over npm as far as I can tell (especially in 2024).

But aside from my opinions around it, I think we should either use `npm` or `yarn` and then have all of our tooling depending on one or the other 😄

**Review by tpluscode — APPROVED** [review]

**Comment by tpluscode** [comment]
Ok with squash? @spwoodcock

**Review by ludovicm67 — APPROVED** [review]

**Pull request merged**
