### PR TITLE
Fix linting

### PR DESCRIPTION
**Pull request by tpluscode**
The lint job was now failing on CI because the packages we compiled in `prepare` script. This is still necessary for the demos to build but removing webpack is the next thing I should do because we're using an ancient version anyway

### CODE REVIEW

**Comment by tpluscode** [comment]
As said above, webpack 4 needs to be removed because it does not play well with modern setup

**Comment by ludovicm67** [comment]
@tpluscode so you want to have this merged now, or wait another PR to update the setup first?

I just wanted to point that if we merge this PR in the current state, the demo part will not work anymore.

**Comment by tpluscode** [comment]
The deployment is broken anyway from what I can see so we can just as well merge now. I'm working on replacing webpack with vite already too so waiting is also an option

**Comment by tpluscode** [comment]
There isn't much left after syncing with `master` :)

**Review by ludovicm67 — APPROVED** [review]
Thank you @tpluscode for all your work on improving the whole build setup in order to have it more modern! 👏 

The thing is able to build a lot faster, and it works!

**Review by spwoodcock — APPROVED** [review]

**Pull request merged**
