### PR TITLE
docs: storybook

### LINKED ISSUE #124: Hot-reloading for Vite dev server
### Issue

- Currently we use `npm run start`, which uses `vite` to run the dev server.
- A `prestart` script is used to run `tsc` so that TS modules are compiled to JS before the server starts.
- Ideally we would have hot-reloading, so that changes to the components would reflect on the running demo page.

### Possible Solutions

1. Ideally the Vite configuration can handle this somehow. I assume it's not picking up the `.ts` files as the `.js` files are referenced everywhere.
2. A package like `npm-run-all` or `concurrently` (or `pnpm`) to run multiple scripts at once.
  a. We could have a script to run `tsc --watch` and another for `vite` to run together.
3. Something else!

### PR DESCRIPTION
**Pull request by tpluscode**
I now completely replaced the manual vite setup of Polyer-based API and demo pages with Storybook. 

Storybook support [Custom Elements Manifest](https://github.com/webcomponents/custom-elements-manifest) which is also used by IDEs to provide suggestions for elements and their attributes. Manifests are now included in the packages

Closes #124

### CODE REVIEW

**Comment by tpluscode** [comment]
The only missing piece from the previous demo pages are the supplementary descriptions which seem to have no place in the Web Components setup. I am yet to figure out how to bring them back

**Comment by tpluscode** [comment]
Ah, it's actually quite simple with JSDoc :)

**Review by spwoodcock — APPROVED** [review]
This is so much nicer 😄 
More intuitive to navigate, faster to load, great layout - love it!

**Comment by tpluscode** [comment]
Storybook is a marvellous piece of software 🙂

**Comment by spwoodcock** [comment]
Just doing a few more tests - two things I have noticed 😄 

If I run the watcher in the background to compile to ts and edit a component, I get an error:
image

I have to refresh storybook to reload the component.


And also, I don't think this is related to storybook, but the map height is not reactive to the parent div.
I only noticed because I have to scroll a lot on my small laptop screen.

I tried to modify the `Control.stories.ts` as a test:

```js
  render: ({ style, ...args }) => html`
  <div style="height: 200px;">
    <ol-map ${spread(args)} style="${styleMap(style)}">
      <ol-layer-openstreetmap></ol-layer-openstreetmap>
      <ol-control id="top-right">
        <button>Top right button</button>
      </ol-control>
      <ol-control id="bottom-left">
        <button>Bottom left button</button>
      </ol-control>
    </ol-map>
  </div>`,
```

> Incidentally, setting the width property does modify the map! Just not setting the height.

**Comment by spwoodcock** [comment]
For the first issue, do you think it's possible to compile the ts on the fly as part of the vite server underneath storybook? I'm hoping if the ts compile is internal to storybook, it might avoid this error, but then again maybe not! (as it's registering the custom component each time it loads the re-compiled file)

**Comment by tpluscode** [comment]
> CustomElementRegistry.define: 'X' has already been defined as a custom element

That has nothing to do with compilation, nor, strictly speaking with Storybook itself. A page has only a single instance of `CustomElementRegistry` and trying to register the same tag name twice results in the error. Very common problem for ho module reload and web components. 

Storybook docs mention this in the [Webpack section](https://storybook.js.org/docs/get-started/web-components-webpack5#hot-module-reloading-hmr).

> Therefore, the best approach for now is to do full page reloads while developing.

There's [this snippet](https://github.com/storybookjs/storybook/tree/master/app/web-components#user-content-setup-page-reload-via-hmr) in the source which will force a reload but HMR works well enough for story modification so I have not incorporated it. You could also monkey-patch `CustomElementRegistry.define` and reload the page when this error is thrown...

**Comment by tpluscode** [comment]
> If I run the watcher in the background to compile to ts and edit a component, I get an error:

By the way, you do not need to compile in the first place. Storybook works with TS directly

**Comment by tpluscode** [comment]
@spwoodcock I changed the styling of the map so that it fills its container. On the `Docs` pages, each map had 400px. Smaller seemed a little to tight.

On individual story pages, the maps will fill the entire available space.

**Comment by spwoodcock** [comment]
Thanks for clarifying 😄

Is it worth adding the CSS `#root-inner` info to the docs on ol-map? I can do that 👍

**Comment by tpluscode** [comment]
`#root-inner` is a Storybook container.

Else, some docs could be useful to explain that the map requires a height, either explicit or by using flexbox to fill the containing element

**Comment by spwoodcock** [comment]
Ah of course, thanks!

I can add that info to the docstring 👍

Realised I made a small typo in the readme too, so will PR together

**Pull request merged**
